version: '3.1'

services:
  console-dev:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./console-server.conf:/console-server.conf
      - ./build/rollup:/console-server/src/ai/backend/console/static
    environment:
      - BACKEND_ENDPOINT_TYPE=api
    command: /bin/bash -c "redis-server --daemonize yes && python3 -m ai.backend.console.server -f /console-server.conf"
    networks:
      - backend
  console:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    volumes:
      - ./console-server.conf:/console-server.conf
      - ./certificates:/etc/certificates
    environment:
      - BACKEND_ENDPOINT_TYPE=api
    command: /bin/bash -c "redis-server --daemonize yes && python3 -m ai.backend.console.server -f /console-server.conf"
    networks:
      - backend
networks:
  backend:
    driver: bridge
